### ISSUE TITLE
Support separate accounts for route53 and SES

### ISSUE THREAD

**Issue by chancez** [cloudposse/terraform-aws-ses#24]
## Describe the Feature

Support creating route53 records in a different account from the SES domain.

## Expected Behavior

Create route53 domain verification records in a different account from the SES Domain.

## Use Case

This module currently uses the same implicit AWS provider for all resources, and thus, cannot support the case where the route53 zone for verification is in a separate account for where the SES domain/user/etc are created.

## Describe Ideal Solution

This module should specify at least two AWS providers with different aliases so that a user can specify an AWS provider for route53 and SES separately to support this use-case.

## Alternatives Considered

Not using the module/forking it.

**Comment by Gowiem** [comment]
@chancez we typically don't add support for creating resources in different accounts via a single module as the multiple `provider` block pattern to do so is very funky for the more standard use-case. 

Since your use-case is specific to you, what we would suggest is that use the SES module to create your SES resources, disable the domain verification resources, and then create your domain verification resources outside of the module using your separate provider block.
