### ISSUE TITLE
Add tests for CloudFlare

### ISSUE THREAD

**Issue by 3h4x** [cloudposse/terraform-aws-ses#9]
## Describe the Feature
Functionality to create CloudFlare verification added in https://github.com/cloudposse/terraform-aws-ses/pull/8 should be tested. 
https://github.com/cloudposse/terraform-aws-ses/pull/8/files#diff-7a370d8342e7203b805911c92454f0f4R33-R41
https://github.com/cloudposse/terraform-aws-ses/pull/8/files#diff-7a370d8342e7203b805911c92454f0f4R59-R71

## Expected Behavior

Tests should pass :)

**Comment by JohnShortland** [comment]
@3h4x 

You can close this for now as  I will create new merge request as I have added DNSimple also but before submitting I need to add conditional validation.

**Comment by Gowiem** [comment]
@3h4x @JohnShortland Ya'll still need this to be addressed?

**Comment by JohnShortland** [comment]
@Gowiem Currently I need to use DNSimple but I think the best option would be to have some conditional validation to allow people choose between Route53, Cloudflare or DNSimple doing the vaildation, time got away from me on updating it.

**Comment by Gowiem** [comment]
@JohnShortland the problem with that is the `provider` block: Typically when you want to involve multiple providers in one module it can cause issues due to not having configuration for one over another. And there is no `count` on provider blocks so you have to provide config otherwise 💥 . 

I don't see us supporting that, but maybe I'm missing something from your PR? Either way, I'm going to close this out since we closed #8. If you put up support for another DNS registry as part of this repo then please be sure to ping me and we'll see what we can do.
